title: Brendan Almonte
name: Brendan Almonte
description: Software Engineer
url: /

github_username:  almonteb
facebook_username: almonteb
twitter_username: almonteb
linkedin_username: almonteb
instagram_username: almonteb
public_key_url: https://keybase.io/almonteb

avatar: True
avatar_img_path: https://avatars1.githubusercontent.com/u/42337

front_img: True
front_img_path: imgs/background.jpg

favicon_img: True
favicon_img_path: imgs/favicon.ico

exclude:
  - LICENSE
  - README.md
